// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8nuAWDaQdCTp4iifFZOCEVi0e65nayUw',
    appId: '1:751727484518:web:2e0a3eb7cef5ef874417a7',
    messagingSenderId: '751727484518',
    projectId: 'flutterauthsti',
    authDomain: 'flutterauthsti.firebaseapp.com',
    storageBucket: 'flutterauthsti.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTB6JXuj0-OVm2SkXoK6xDFQEUzhbDPWc',
    appId: '1:751727484518:android:45b62380f518528b4417a7',
    messagingSenderId: '751727484518',
    projectId: 'flutterauthsti',
    storageBucket: 'flutterauthsti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrXZuF0Tp8y1q60_oi5nQ2S1aHYhiwS1U',
    appId: '1:751727484518:ios:92a9249e8bad43854417a7',
    messagingSenderId: '751727484518',
    projectId: 'flutterauthsti',
    storageBucket: 'flutterauthsti.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8nuAWDaQdCTp4iifFZOCEVi0e65nayUw',
    appId: '1:751727484518:web:cbc749faa8d817bb4417a7',
    messagingSenderId: '751727484518',
    projectId: 'flutterauthsti',
    authDomain: 'flutterauthsti.firebaseapp.com',
    storageBucket: 'flutterauthsti.firebasestorage.app',
  );
}
